spring:
 application:
  name: hr-guqing-cloud-gateway
 profiles:
  active: dev
server: 
 port: 9001
eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://user:password@127.0.0.1:8761/eureka
  healthcheck:
   enabled: true
  instance:
   prefer-ip-address: true
   hostname: ${spring.cloud.client.ipAddress}
   instance-id: ${spring.cloud.client.ipAddress}:${server.port}
logging:
 level:
  root: INFO
zuul: 
 # ignoredServices: '*'
 ignore-local-service: false
 ignored-patterns: 
 routes:
  busine-greeting:
   path: /guqing/api/greeting/**
   url: forward:/forward
  service-bookstore: 
   path: /guqing/api/bookstore/**
   serviceId: hr-guqing-cloud-bookstore
   
ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000