server:
 port: 8802
spring:
 application:
  name: hr-guqing-cloud-order
 profiles: 
  active: dev
eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
   defaultZone: http://user:password@127.0.0.1:8761/eureka
  healthcheck:
   enabled: true
  instance:
   prefer-ip-address: true
   hostname: ${spring.cloud.client.ipAddress}
   instance-id: ${spring.cloud.client.ipAddress}:${server.port}
logging:
 level:
  root: INFO